/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package studentinformation;

import java.io.File;
import java.io.IOException;
import java.net.URL;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author hp
 */
public class Information extends javax.swing.JFrame {

    /**
     * Creates new form Information
     */
    public Information() {
        initComponents();
        hidemethod();
        setLocationRelativeTo(null);
    }
    public void hidemethod()
    {
        sidebar.setVisible(false);
        sidebar.setEnabled(false);
        jLabel14.setVisible(false);
        jLabel13.setVisible(false);
        jLabel12.setVisible(false);
        jLabel11.setVisible(false);
        jLabel10.setVisible(false);
        jLabel8.setVisible(false);
        jLabel7.setVisible(false);
        jLabel4.setVisible(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        profilepic = new javax.swing.JLabel();
        usernametext = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        useremailtext = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        dot = new javax.swing.JLabel();
        calendericon = new javax.swing.JLabel();
        searchicon = new javax.swing.JLabel();
        timetableicon = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        roompartnertextfield = new javax.swing.JTextField();
        cpitextfield = new javax.swing.JTextField();
        roomtextfield = new javax.swing.JTextField();
        hosteltextfield = new javax.swing.JTextField();
        dateofbirthtextfield = new javax.swing.JTextField();
        mobiletextfield = new javax.swing.JTextField();
        emailtextfield = new javax.swing.JTextField();
        nametextfield = new javax.swing.JTextField();
        sidebar = new javax.swing.JPanel();
        search = new javax.swing.JTextField();
        goicon = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        calender = new javax.swing.JLabel();
        timetable = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        crossicon = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentinformation/images/MNNIT2.png"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(101, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(128, 128, 128))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(6, 6, 89));

        usernametext.setEditable(false);
        usernametext.setBackground(new java.awt.Color(6, 6, 89));
        usernametext.setFont(new java.awt.Font("Microsoft New Tai Lue", 0, 36)); // NOI18N
        usernametext.setForeground(new java.awt.Color(255, 255, 255));
        usernametext.setBorder(null);

        jLabel2.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Welcome !!");

        useremailtext.setEditable(false);
        useremailtext.setBackground(new java.awt.Color(6, 6, 89));
        useremailtext.setFont(new java.awt.Font("Segoe UI Semilight", 2, 18)); // NOI18N
        useremailtext.setForeground(new java.awt.Color(255, 255, 255));
        useremailtext.setBorder(null);
        useremailtext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                useremailtextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(profilepic, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(useremailtext, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(usernametext, javax.swing.GroupLayout.DEFAULT_SIZE, 417, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(usernametext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(useremailtext, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(profilepic, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 550, 200));

        jPanel3.setBackground(new java.awt.Color(6, 6, 89));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dot.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentinformation/images/icons8_Coderwall_26px.png"))); // NOI18N
        dot.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        dot.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dotMouseClicked(evt);
            }
        });
        jPanel3.add(dot, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 0, -1, 45));

        calendericon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentinformation/images/icons8_Calendar_1_26px.png"))); // NOI18N
        calendericon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        calendericon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                calendericonMouseClicked(evt);
            }
        });
        jPanel3.add(calendericon, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 570, -1, -1));

        searchicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentinformation/images/icons8_Search_26px.png"))); // NOI18N
        searchicon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        searchicon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchiconMouseClicked(evt);
            }
        });
        jPanel3.add(searchicon, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, -1, -1));

        timetableicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentinformation/images/icons8_Planner_26px.png"))); // NOI18N
        timetableicon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        timetableicon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                timetableiconMouseClicked(evt);
            }
        });
        jPanel3.add(timetableicon, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 490, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentinformation/images/icons8_Logout_Rounded_Left_26px.png"))); // NOI18N
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 640, -1, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 680));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jLabel4.setText("Room No :");
        jPanel5.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, 110, 30));

        jLabel7.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jLabel7.setText("Mobile No :");
        jPanel5.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 110, 30));

        jLabel8.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jLabel8.setText("Date of Birth : ");
        jPanel5.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 150, 30));

        jLabel10.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jLabel10.setText("Room Partner :");
        jPanel5.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 380, 150, 30));

        jLabel11.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jLabel11.setText("Hostel Name :");
        jPanel5.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, 130, 30));

        jLabel12.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jLabel12.setText("CPI :");
        jPanel5.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, 60, 30));

        jLabel13.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jLabel13.setText("Email ID :");
        jPanel5.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 100, 30));

        jLabel14.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jLabel14.setText("Name :");
        jPanel5.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 70, 30));

        roompartnertextfield.setEditable(false);
        roompartnertextfield.setFont(new java.awt.Font("Microsoft Tai Le", 1, 18)); // NOI18N
        roompartnertextfield.setForeground(new java.awt.Color(0, 0, 102));
        roompartnertextfield.setBorder(null);
        jPanel5.add(roompartnertextfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 380, 300, 30));

        cpitextfield.setEditable(false);
        cpitextfield.setFont(new java.awt.Font("Microsoft Tai Le", 1, 18)); // NOI18N
        cpitextfield.setForeground(new java.awt.Color(0, 0, 51));
        cpitextfield.setBorder(null);
        jPanel5.add(cpitextfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 330, 100, 30));

        roomtextfield.setEditable(false);
        roomtextfield.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 18)); // NOI18N
        roomtextfield.setForeground(new java.awt.Color(0, 0, 102));
        roomtextfield.setBorder(null);
        jPanel5.add(roomtextfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 280, 110, 30));

        hosteltextfield.setEditable(false);
        hosteltextfield.setFont(new java.awt.Font("Microsoft Tai Le", 1, 18)); // NOI18N
        hosteltextfield.setForeground(new java.awt.Color(0, 0, 102));
        hosteltextfield.setBorder(null);
        jPanel5.add(hosteltextfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 230, 300, 30));

        dateofbirthtextfield.setEditable(false);
        dateofbirthtextfield.setFont(new java.awt.Font("Microsoft YaHei", 0, 18)); // NOI18N
        dateofbirthtextfield.setForeground(new java.awt.Color(0, 0, 102));
        dateofbirthtextfield.setBorder(null);
        jPanel5.add(dateofbirthtextfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 180, 300, 30));

        mobiletextfield.setEditable(false);
        mobiletextfield.setFont(new java.awt.Font("Microsoft YaHei", 0, 18)); // NOI18N
        mobiletextfield.setForeground(new java.awt.Color(0, 0, 102));
        mobiletextfield.setBorder(null);
        jPanel5.add(mobiletextfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, 300, 30));

        emailtextfield.setEditable(false);
        emailtextfield.setFont(new java.awt.Font("Segoe UI Semilight", 3, 16)); // NOI18N
        emailtextfield.setForeground(new java.awt.Color(0, 0, 102));
        emailtextfield.setBorder(null);
        jPanel5.add(emailtextfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, 300, 30));

        nametextfield.setEditable(false);
        nametextfield.setFont(new java.awt.Font("Microsoft Tai Le", 1, 18)); // NOI18N
        nametextfield.setForeground(new java.awt.Color(0, 0, 102));
        nametextfield.setBorder(null);
        jPanel5.add(nametextfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, 300, 30));

        sidebar.setBackground(new java.awt.Color(6, 6, 89));
        sidebar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        search.setBackground(new java.awt.Color(6, 6, 89));
        search.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 24)); // NOI18N
        search.setForeground(new java.awt.Color(255, 255, 255));
        search.setBorder(null);
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        sidebar.add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 140, 30));

        goicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentinformation/images/icons8_Right_26px.png"))); // NOI18N
        goicon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        goicon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                goiconMouseClicked(evt);
            }
        });
        sidebar.add(goicon, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, -1, 30));
        sidebar.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 120, 10));

        calender.setFont(new java.awt.Font("Tempus Sans ITC", 0, 28)); // NOI18N
        calender.setForeground(new java.awt.Color(255, 255, 255));
        calender.setText("Calender");
        calender.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        calender.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                calenderMouseClicked(evt);
            }
        });
        sidebar.add(calender, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 130, 40));

        timetable.setFont(new java.awt.Font("Tempus Sans ITC", 0, 28)); // NOI18N
        timetable.setForeground(new java.awt.Color(255, 255, 255));
        timetable.setText("Time Table");
        timetable.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        timetable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                timetableMouseClicked(evt);
            }
        });
        sidebar.add(timetable, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 130, 50));

        jLabel6.setFont(new java.awt.Font("Tempus Sans ITC", 0, 28)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Logout");
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        sidebar.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 110, 40));

        crossicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentinformation/images/icons8_Delete_24px.png"))); // NOI18N
        crossicon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        crossicon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                crossiconMouseClicked(evt);
            }
        });
        sidebar.add(crossicon, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 0, -1, 30));

        jPanel5.add(sidebar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 205, 310));

        jPanel6.setBackground(new java.awt.Color(6, 6, 89));

        jLabel9.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Developed by Lokesh Chandra");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(0, 370, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel5.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, 550, 30));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 550, 480));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel8.setBackground(new java.awt.Color(6, 6, 89));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 680, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 0, 50, 680));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void useremailtextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_useremailtextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_useremailtextActionPerformed

    private void dotMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dotMouseClicked
        // TODO add your handling code here:
        sidebar.setVisible(true);
        sidebar.setEnabled(true);
    }//GEN-LAST:event_dotMouseClicked

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchActionPerformed

    private void crossiconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_crossiconMouseClicked
        // TODO add your handling code here:
        sidebar.setVisible(false);
        sidebar.setEnabled(false);
    }//GEN-LAST:event_crossiconMouseClicked

    private void searchiconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchiconMouseClicked
        // TODO add your handling code here:
        sidebar.setVisible(true);
        sidebar.setEnabled(true);
    }//GEN-LAST:event_searchiconMouseClicked

    private void timetableiconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_timetableiconMouseClicked
        // TODO add your handling code here:
         try
       {
           URL urlpath= getClass().getResource("/studentinformation/time_table.pdf");
           Runtime.getRuntime().exec("rundll32 url.dll, FileProtocolHandler " + urlpath);
       }
       catch(IOException e)
       {
           System.out.println(e);
       }
    }//GEN-LAST:event_timetableiconMouseClicked

    private void calendericonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_calendericonMouseClicked
        // TODO add your handling code here:
        try
       {
           URL urlpath= getClass().getResource("/studentinformation/acadcal_2018_19.pdf");
           Runtime.getRuntime().exec("rundll32 url.dll, FileProtocolHandler " + urlpath);
       }
       catch(IOException e)
       {
           System.out.println(e);
       }
    }//GEN-LAST:event_calendericonMouseClicked

    private void timetableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_timetableMouseClicked
        // TODO add your handling code here:
        try
       {
           URL urlpath= getClass().getResource("/studentinformation/time_table.pdf");
           Runtime.getRuntime().exec("rundll32 url.dll, FileProtocolHandler " + urlpath);
       }
       catch(IOException e)
       {
           System.out.println(e);
       }
    }//GEN-LAST:event_timetableMouseClicked

    private void calenderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_calenderMouseClicked
        // TODO add your handling code here:
       /* if (java.awt.Desktop.isDesktopSupported()) {
        try {
            File myFile = new File("C:\\Users\\hp\\Documents\\NetBeansProjects\\StudentInformation\\src\\studentinformation\\images\\acadcal_2018_19.pdf");
            java.awt.Desktop.getDesktop().open(myFile);
            } catch (IOException ex) {
        // no application registered for PDFs
                }
               }*/
       try
       {
           
           URL urlpath= getClass().getResource("/studentinformation/acadcal_2018_19.pdf");
           Runtime.getRuntime().exec("rundll32 url.dll, FileProtocolHandler " + urlpath);
       }
       catch(IOException e)
       {
           System.out.println(e);
       }
    }//GEN-LAST:event_calenderMouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        LogIn ln = new LogIn();
        ln.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
         LogIn ln = new LogIn();
        ln.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel5MouseClicked
   public void showmymethod()
   {
       jLabel14.setVisible(true);
        jLabel13.setVisible(true);
        jLabel12.setVisible(true);
        jLabel11.setVisible(true);
        jLabel10.setVisible(true);
        jLabel8.setVisible(true);
        jLabel7.setVisible(true);
        jLabel4.setVisible(true);
   }
   public void seticons(String choose)
   {
       String str = "/studentinformation/photos/" + choose + ".png";
    // profilepic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentinformation/photos/2017CA25.png")));
       profilepic.setIcon(new javax.swing.ImageIcon(getClass().getResource(str)));
   }
    PreparedStatement pstmt = null;
    ResultSet rs = null;
    private void goiconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_goiconMouseClicked
        // TODO add your handling code here:
        String reg = search.getText();
        if(reg!=null)
        {
        sidebar.setVisible(false);
        sidebar.setEnabled(false);
        
        showmymethod();
        
        String names=null,emails=null,dob=null,roomno=null,rpartner=null,mobile=null,cpi=null,hname=null;
        try
        {
         MySQLConnection msc = new MySQLConnection();
         pstmt = MySQLConnection.conn.prepareStatement("select * from studentinfo where RegNo =?"); // select table into database
         pstmt.setString(1, reg);
         rs = pstmt.executeQuery();
         while(rs.next())
            {
                dob = rs.getString("DateOfBirth");
                names = rs.getString("Name");
                emails = rs.getString("Email");
                mobile = rs.getString("MobileNo");
                hname = rs.getString("HostelName");
                roomno = rs.getString("RoomNo");
                cpi = rs.getString("CPI");
                rpartner = rs.getString("RoomPartner");
            }
           nametextfield.setText(names);
           emailtextfield.setText(emails);
           mobiletextfield.setText(mobile);
           dateofbirthtextfield.setText(dob);
           hosteltextfield.setText(hname);
           roomtextfield.setText(roomno);
           cpitextfield.setText(cpi);
           roompartnertextfield.setText(rpartner);
        }
        catch(SQLException e)
        {
            System.out.println(e);
        }
        }
        else
             JOptionPane.showMessageDialog(null, "Please Enter Registration Number......!!");
    }//GEN-LAST:event_goiconMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Information.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Information.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Information.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Information.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Information().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel calender;
    private javax.swing.JLabel calendericon;
    private javax.swing.JTextField cpitextfield;
    private javax.swing.JLabel crossicon;
    private javax.swing.JTextField dateofbirthtextfield;
    private javax.swing.JLabel dot;
    private javax.swing.JTextField emailtextfield;
    private javax.swing.JLabel goicon;
    private javax.swing.JTextField hosteltextfield;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField mobiletextfield;
    private javax.swing.JTextField nametextfield;
    public javax.swing.JLabel profilepic;
    private javax.swing.JTextField roompartnertextfield;
    private javax.swing.JTextField roomtextfield;
    private javax.swing.JTextField search;
    private javax.swing.JLabel searchicon;
    private javax.swing.JPanel sidebar;
    private javax.swing.JLabel timetable;
    private javax.swing.JLabel timetableicon;
    public javax.swing.JTextField useremailtext;
    public javax.swing.JTextField usernametext;
    // End of variables declaration//GEN-END:variables
}
