/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package studentinformation;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author hp
 */
public class LogIn extends javax.swing.JFrame {

    /**
     * Creates new form LogIn
     */
    public LogIn() {
        initComponents();
        check();
       setLocationRelativeTo(null);
    }
public void check()
{
    if(box1!=null && box2!=null)
    {
        usertextfield.setText(box1);
        passwordtextfield.setText(box2);
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        usertextfield = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        passwordtextfield = new javax.swing.JPasswordField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        play = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentinformation/images/MNNIT2.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 14, 310, 420));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentinformation/images/icons8_Lock_26px.png"))); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, -1, 30));

        usertextfield.setBackground(new java.awt.Color(204, 204, 204));
        usertextfield.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 18)); // NOI18N
        usertextfield.setBorder(null);
        jPanel2.add(usertextfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, 170, 30));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentinformation/images/icons8_User_Male_26px_1.png"))); // NOI18N
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, -1, 30));

        passwordtextfield.setBackground(new java.awt.Color(204, 204, 204));
        passwordtextfield.setBorder(null);
        jPanel2.add(passwordtextfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, 170, 30));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, 170, 10));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, 170, 20));

        play.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentinformation/images/icons8_Play_52px_1.png"))); // NOI18N
        play.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        play.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                playMouseClicked(evt);
            }
        });
        jPanel2.add(play, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 140, 50, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 440, 590, 220));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    PreparedStatement pstmt = null;
    ResultSet rs = null;
    public static  String box1 = null,box2 = null;
    private void playMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_playMouseClicked
        // TODO add your handling code here:
        
        try 
        {
            String reg = usertextfield.getText();
            String pass = passwordtextfield.getText();
            String dob = null,names = null,emails=null;
            MySQLConnection msc = new MySQLConnection();
            
            pstmt = MySQLConnection.conn.prepareStatement("select * from studentinfo where RegNo =?"); // select table into database
            pstmt.setString(1, reg);
            rs = pstmt.executeQuery();
            while(rs.next())
            {
                dob = rs.getString("Password");
                names = rs.getString("Name");
                emails = rs.getString("Email");
            }
            if(pass.equals(dob))
            {
                box1 =  usertextfield.getText();
                box2 =  passwordtextfield.getText();
                
                Information in = new Information();
                in.usernametext.setText(names);
                in.useremailtext.setText(emails);
                in.seticons(box1);
                in.setVisible(true);
                dispose();
            }
            else
                JOptionPane.showMessageDialog(null, "Reg No. or password is wrong..!!!!");
        }
        catch(SQLException e)
        {
            System.out.println(e);
        }
        
    }//GEN-LAST:event_playMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LogIn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPasswordField passwordtextfield;
    private javax.swing.JLabel play;
    private javax.swing.JTextField usertextfield;
    // End of variables declaration//GEN-END:variables
}
